### ISSUE TITLE
Configuration design: Resources specified by URI (e.g. icons)

### ISSUE THREAD

**Issue by malex984** [hilbert/hilbert-cli#18]
Note: this is a separation of super-issue  hilbert/hilbert-cli#13

**General: 1.3** I see in the Google Doc that some objects have an "icon uri" that does not appear in the YAML file. The icons have to be placed in the "public" directory of the server for them to be accessible and they're kind of UI-dependent, so for now we could keep them out of the config and instead use png files within (public/icons/app) whose name is the app id, for instance.

**Comment by porst17** [comment]
Using just the id to name the icon files seems reasonable.

However: Who puts the icon files there? I guess they have to be pulled from the CMS, i.e. this should be part of the external syncing of the config.

**Comment by elondaits** [comment]
Yes... it could be synced. Alternatively you can create a symbolic link from the directory that holds the icons to `public/images/icons` or something like that. But in any case you never specify the full URL, either:
- Nothing and use the app id
- A file name

**Comment by malex984** [comment]
I thought users would be able to put icons to CMS and specify static URLs in the configuration...
Just like it will be done with smaller WebGl apps.

**Comment by elondaits** [comment]
In a different web server? We could eventually support that at some point, but it's a different way of doing things which would require a separate code path and many different considerations in the html/css code. Plus it has some drawbacks.

**Comment by porst17** [comment]
I suggest to keep the icons out of the config and rely on syncing for now. Support of URIs can be added in a backwards compatible manner later if requested.

**Comment by malex984** [comment]
Other necessary **external** resources are `docker-compose.yml` files defining the services and applications **for this project**. NOTE: each new application will require another such definition in a such file.  

Possible solutions:
1. install `docker-compose.yml` via Server Configuration .RPM and use them similarly to the ssh keys (see #25)
   - not clear how to add a new application definition
2. put those definitions of services and applications into directly into the general config file
   - will over-complicate general configuration file
3. allow users to put them to some accessible external location which will be available to the management container (e.g. CMS or some other WebServer) via some syncing method.
   - more complicated procedure for configuration synchronization

Currently there is a single external configuration file: [`docker-compose.yml`](https://github.com/hilbert/hilbert-cli/blob/devel/config/templates/docker-compose.yml) defining all services and applications. It may be put alongside with the general high-level configuration file.

This question may be related to #9

**Comment by elondaits** [comment]
Why not a single directory accesible by the server that has all files with a scheme such as one of these:

```
apps/<app_id>/docker-compose.yml
apps/<app_id>/<version>/docker-compose.yml
apps/<app_id>.yml
apps/<app_id>_<version>.yml

```

?

We don't need to concern with how they get there. They could be rsynced, sftped, a remote volume mounted, etc.

But we don't need to worry with specifying each of them in the cfg either... just the base path or url.

I would not put them in a web server unless HTTP were chosen as the way for the stations to pull cfgs and scripts from the server. But if that's the way it's done then it's the same thing... you build an URL instead of a PATH.

**Comment by malex984** [comment]
IMO there may be different versions of the same application running on a station (e.g. in a test station). Therefore version has to be a part of `app_id`.

> single directory that has all files with a scheme ... But we don't need to worry with specifying each of them in the cfg either... just the base path or url.

I am fine with that. What about a small generalization for configuration directory:

```
<BASE_CMS_CONFIG_PATH_OR_URL>/
 - config.yml # the general high-level config file
 - dc_services/<service_id>.yml # low-level service definitions run-able with Docker-Compose
 - dc_applications/<app_id>.yml # low-level application definitions run-able with Docker-Compose
 - icons/icon_id.ico # icons
 - resource_type/resource_id_from_config.Type_Suffix # maybe even general resources?
```

> We don't need to concern with how they get there. They could be rsynced, sftped, a remote volume mounted, etc.

Sorry but it really seems to be part of Hilbert-Synchronization, which has to obtain the general configuration file AND all its dependencies from CMS in an atomic way.

> I would not put them in a web server unless HTTP were chosen as the way for the stations to pull cfgs and scripts from the server. 
> But if that's the way it's done then it's the same thing... you build an URL instead of a PATH.

I imagine, CMS could serve the configuration directory structure mentioned above (`BASE_CMS_CONFIG_PATH_OR_URL/`)  via HTTP alternatively to the current sFTP access...

**Comment by porst17** [comment]
1. Do services and apps live in the same namespace? If they do, the schema should be
   
   ```
   docker-compse/<service_or_app_id>.yml
   ```
   
   Otherwise
   
   ```
   docker-compse/services/<service_id>.yml
   docker-compse/applications/<app_id>.yml
   ```
   
   Don't use `dc_*`. Nobody except @malex984 knows what that means. Instead, `docker-compose` is something everybody can ask Google for if they have no clue. Again, this is externally facing config and chosen names should better be descriptive than short.
2. Hilbert should only access local config. Syncing with remote data is separate. See #29.

**Comment by elondaits** [comment]
Icons are not part of the config. They go into the public web folder and they are readable by the www user, while neither of those apply to the cfg (on the contrary, cfg is not accesible through the front end web server nor readable by that user if possible). Symbolic linking is not appropriate either because web security is usually defined hierarchically and you shouldn't place public files inside a very secure directory.

Also, icons are not part of the cfg because they can go into a repository (while cfg never does) and because if you have several servers (dev, staging, production) the same icon set is deployed to all, while cfgs are private to each server (cfgs are always different between different servers).

I would say don't worry about icons in the cfg at this stage... at the moment we're the only ones providing the icons and their format (size, format, characteristics) might still change as the visual look is refined. We can match icons using the app id and the directory hosting the icons can be kept in the front end cfg. The icons, in fact, are only relevant to the ui.... not the whole system nor the cli.

**Comment by malex984** [comment]
@elondaits I would also like to **skip** application's icons at this stage. In the very worst case - they may even be directly embedded as binary data into the general configuration :-/

But conceptually i consider **icons** as **part of application definition for the Dashboard**: adding a new application to the general configuration (on the CMS) may actually involve a creation of a new application icon.

**Comment by malex984** [comment]
Currently only `Service::file` and `Application::file` reference external (e.g. `docker-compose.yml`) resources. Their location is supposed to be relative to the main Hilbert YAML Configuration file. 
Icons may be handled in the same way.

Thus no pre-defined naming schema for external resources has to be defined right now. 
Relative URIs will start at the location of the main Hilbert Configuration file. This should be enough for now. @porst17 @elondaits Are you OK with that?

**Comment by porst17** [comment]
I am OK with that, but in the long run I would rather prefer to have sane defaults for these values. i.e. a default naming scheme that is used if no file name is provided in the config. This helps to keep the config files short.

**Comment by malex984** [comment]
@porst17 I agree. There are default values wherever possible: both `Service::file` and `Application::file` have default value: `docker-compose.yml` (if it is absent and corresponding **mandatory** `Service::type` or `Application::type` is `compose`). 

Do you see any further mandatory fields that can be set by default?

**Comment by porst17** [comment]
This issue is not about discussing defaults for mandatory fields besides the URIs. If there is really need to discuss this, please open a separate issue specifically addressing defaults values.

**Comment by malex984** [comment]
Sorry i went off topic there. 

I suggest we continue this discussion later when we get more external resources to deal with.

**Comment by elondaits** [comment]
We should stop dragging icons into the discussion:

- Icons are not part of the hilbert cli, it doesn't use them. They're specifically a part of the ui.
- Icons are not implementation independent. The icon requirements are dictated by the technical capabilities and limitations of the web ui. Each platform defines the requirements of its icons. 
- Icons are placed in a public web directory which is owned by the UI. This is a security sensitive thing. The full path to the icons will depend on the configuration of the ui.

Also:

- We don't configure the full path to docker images. We use a repository scheme for that where the image is retrieved based on an identifier... so if app icons are likewise indexed by the app identifier in a "repository" of sorts (e.g. a public web directory) I consider it no worse than the rest of the system.
