### ISSUE TITLE
Configuration design: Do not use null | void

### ISSUE THREAD

**Issue by elondaits** [hilbert/hilbert-cli#26]
In some parts of the latest draft of the cfg the words "void" and "null" are used. It's not a good idea... they're words from programming languages (not domain words) and we would be faking them because for instance in JS void does not exist and undefined variables are 'undefined' and not 'null'. 

We would also need to include "null" as an option in all of our validation code.

The normal thing in a cfg is that you either not include a key, or comment it out... if you include it then you MUST give it a valid strongly typed value.

cc: @porst17

Note: this is a part of super-issue "Configuration Design": hilbert/hilbert-cli#13

**Comment by malex984** [comment]
Agreed. 

As a side note: `null` is defined in YAML and used to indicate a lack of value (see: http://yaml.org/type/null.html). Currently it is only used to indicate optional (absent) data fields.

**Comment by elondaits** [comment]
YAML is a data serialization language, much like JSON... so it supports a lot of advanced features that are useful for serialization, such as null. But not all of those features are a good idea when using YAML for encoding cfg files.

**Comment by malex984** [comment]
I see. No use for YAML-specific things. It seems we will end-up using a subset of YAML which is as close to JSON as possible...

**Comment by porst17** [comment]
YAML still has plenty of advantages for defining list, maps, multi-line strings, ...

Even though the used subset might be as expressive as JSON, the config will be much more readable in YAML.

**Comment by porst17** [comment]
@malex984 Are the changes reflected in the current draft of the config? If so, please post the relevant parts here and close the issue.

**Comment by malex984** [comment]
Ok, it is reflected in Configuration Design (super issue) and samples (v0.2.0).

**Comment by porst17** [comment]
> Ok, it is reflected in Configuration Design (super issue) and samples (v0.2.0). 

What about linking the resources directly? Thanks.

**Comment by malex984** [comment]
Sorry, i only used `null` and `void` in the minimal YAML sample in the design draft google document ("Management back-end"). They were eliminated (from the google document) almost immediately after this issue was created, but if possible i would like to avoid public links to that google document. 

The current minimal YAML sample is available at:
https://gist.github.com/malex984/59d2b62c5098eb1005100f9249719505#file-mini_sample-yml

The current real YAML example is at https://gist.github.com/malex984/59d2b62c5098eb1005100f9249719505#file-all_flat-v0-2-0-yml

Super issue: Configuration Design  (#13) also reflects the resulting decision to avoid non-domain words.
